/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        darkNav: '#18191D',
        darkPanel: '#18191D',
        darkCard: '#18191D',
        darkBg: '#0F1015',
        inputDark: '#23242A',
        tagPeach: '#FFF3E8',
        tagMint: '#EAF8F2',
        tagLavender: '#F1EEFC',
        tagIceBlue: '#EAF4FD',
        tagRose: '#FEEDF2',
        tagZinc: '#F4F5F8',
        brandCyan: '#06d6a0',
        brand: {
          50: '#F0F9FF',
          100: '#E0F2FE',
          200: '#BAE6FD',
          300: '#7DD3FC',
          400: '#38BDF8',
          500: '#0EA5E9',
          600: '#0284C7',
          700: '#0369A1',
          800: '#075985',
          900: '#0C4A6E',
          950: '#082F49',
        },
        paperBg: '#FFFFFF',
        paperBorder: '#ECECF0',
        textDark: '#111114',
        textMuted: '#6B7280',
        accentSky: '#4FA8F5',
        pastel: {
          peach: '#FFF3E8',
          mint: '#EAF8F2',
          lavender: '#F1EEFC',
          sky: '#EAF4FD',
          pink: '#FEEDF2',
          neutral: '#F4F5F8',
        },
        status: {
          successText: '#1B8A5A',
          successBg: '#E7F7EF',
          warningText: '#B7791F',
          warningBg: '#FCEFD6',
          errorText: '#C23A3A',
          errorBg: '#FBE2E2',
          infoText: '#3B5BDB',
          infoBg: '#E7EAFB',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      borderRadius: {
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
    },
  },
  plugins: [],
};
